stages:
        - build
        - test

job 1:
        stage: build
        script:
          - make
          - mvn compile
job 2:
        stage: test
        script:
          - make
          - mvn test -Dgroups="Basic"
        only:
          variables:
            - $CI_COMMIT_MESSAGE =~ "testing automation feature"
