stages:
        - build
        - test

job 1:
        stage: build
        script: make
job 2:
        stage: test
        script:
          - make
          - mvn test -Dtest=ValidTests # mvn test -Dgroups="<Test Category>"
        only:
          - master  # only or except: - <name of branch>
