stages:
        - build
        - test

job 1:
        stage: build
        script: make
job 2:
        stage: test
        script:
          - make
          #- mvn test '-Dtest=!InvalidTests#Expression+Variables' # mvn test
          #      -Dgroups="<Test Category>"
          - mvn test '-Dtest=SymbolTableUnitTests'
        #only:
        #  - master  # only or except: - <name of branch>
