stages:
        - build
        - test

job 1:
        stage: build
        script:
          - make
          - mvn compile
job 2:
        stage: test
        script:
          - make
          - mvn test # mvn test -Dgroups="<Test Category>"
        only:
          - lexer_tests # only or except: - <name of branch>
