stages:
        - build
        - test

job 1:
        stage: build
        script:
          - make
          - mvn compile
job 2:
        stage: test
        script:
          - mvn test -Dgroups="Basic"

