stages:
- build
- test

job 1:
  stage: build
  script: make
job 2:
  stage: test
  script:
      - make
      - mvn test -Dtest=CodegenTests#SkipTest+PrintTest+ExitCodeTest+SequenceTest
#      - mvn test -Dtest=AllValidTests
#job 3:
#  stage: test
#  script:
#      - make
#      - mvn test -Dtest=AllInvalidSyntacticTests
#job 4:
#  stage: test
#  script:
#      - make
#      - mvn test -Dtest=AllInvalidSemanticTests



#  - mvn test -Dtest=AllInvalidSyntacticTests,SymbolTableUnitTests
#  - mvn test '-Dtest=SemanticInvalidTests#SemanticArray
#                                         +SemanticExit
#                                         +SemanticExpression
#                                         +SemanticIf
#                                         +SemanticPrint
#                                         +SemanticRead
#                                         +SemanticScope
#                                         +SemanticVariables
#                                         +SemanticWhile
#                                         +SemanticPairs'
    #- mvn test '-Dtest=!InvalidTests#Expression+Variables' # mvn test
    #      -Dgroups="<Test Category>"
    #only:
    #  - master  # only or except: - <name of branch>
